global:
  scrape_interval: 10s
scrape_configs:
  - job_name: app
    static_configs:
      - targets: ['app:8080']
  - job_name: postgresql
    static_configs:
      - targets: ['pg-exporter:9187']
  - job_name: redis
    static_configs:
      - targets: ['redis-exporter:9121']
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
  - job_name: loki
    static_configs:
      - targets: ['loki:3100']
  - job_name: grafana
    static_configs:
      - targets: ['grafana:3000']
